routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('users', 'UserController');
Route::get('/profile', 'HomeController@profile')->name('profile');
Route::put('/profile_update', 'HomeController@profile_update')->name('profile_update');

app/Hobby.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Hobby extends Model{
    protected $primaryKey = 'hob_id';

    protected $fillable = [
        'hob_name'
    ];
}

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model{
    protected $primaryKey = 'pro_id';

    protected $fillable = [
        'pro_name'
    ];

    public function users(){
        return $this->hasMany('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable {
    use Notifiable;

    protected $primaryKey = 'usr_id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'usr_username', 'usr_name', 'usr_email', 'password', 'usr_city', 'pro_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getAuthIdentifierName(){
        return 'usr_id';
    }

    public function profile(){
        return $this->belongsTo('App\Profile', 'pro_id', 'pro_id');
    }

    public function hobbies(){
        return $this->belongsToMany('App\Hobby', 'users_hobbies', 'usr_id', 'hob_id');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Hobby;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class HomeController extends Controller {
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        return view('home');
    }


    public function profile() {
        $user = Auth::user();

        $arrHobbies = array();

        foreach ($user->hobbies as $hobby) {
            $arrHobbies[] = ucfirst(mb_strtolower($hobby->hob_name, 'UTF-8'));
            $user->hobby = implode(", ", $arrHobbies);
        }

        return view('profile', compact('user'));
    }

    public function profile_update(Request $request){
        $user = Auth::user();

        $user->update($request->all());

        $hobbies = $request->get('hobbies');
        $arrHobbies = explode(',', $hobbies);
        $arrHobbie2 = array();

        foreach ($arrHobbies as $hobby) {
            $qHobby = Hobby::where('hob_name', trim(mb_strtoupper($hobby, 'UTF-8')))->first();
            if(!$qHobby){
                $insHobby = Hobby::create(['hob_name' => trim(mb_strtoupper($hobby, 'UTF-8'))]);
                $arrHobbie2[] = $insHobby->hob_id;
            } else {
                $arrHobbie2[] = $qHobby->hob_id;
            }
        }

        $user->hobbies()->sync($arrHobbie2);

        return redirect('profile')->with('status', 'Perfil Actualizado!');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Hobby;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class UserController extends Controller {

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $users =  User::all();
        $auth = Auth::user();

        if($auth->profile->pro_name == "administrator"){
            return view('user', compact('users'));
        } else {
            return redirect('home');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(){
        return redirect('users');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
        return redirect('users');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id){
        return redirect('users');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user){
        $auth = Auth::user();

        if($auth->profile->pro_name == "administrator"){
            $arrHobbies = array();

            foreach ($user->hobbies as $hobby) {
                $arrHobbies[] = ucfirst(mb_strtolower($hobby->hob_name, 'UTF-8'));
                $user->hobby = implode(", ", $arrHobbies);
            }

            return view('edit', compact('user'));
        } else {
            return redirect('home');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user){
        $auth = Auth::user();

        if($auth->profile->pro_name == "administrator"){
            $user->update($request->all());

            $hobbies = $request->get('hobbies');
            $arrHobbies = explode(',', $hobbies);
            $arrHobbie2 = array();

            foreach ($arrHobbies as $hobby) {
                $qHobby = Hobby::where('hob_name', trim(mb_strtoupper($hobby, 'UTF-8')))->first();
                if(!$qHobby){
                    $insHobby = Hobby::create(['hob_name' => trim(mb_strtoupper($hobby, 'UTF-8'))]);
                    $arrHobbie2[] = $insHobby->hob_id;
                } else {
                    $arrHobbie2[] = $qHobby->hob_id;
                }
            }

            $user->hobbies()->sync($arrHobbie2);

            return redirect('users')->with('status', 'Perfil Actualizado!');
        } else {
            return redirect('home');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id){
        return redirect('users');
    }
}

resources/views/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Editar Usuario') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('users.update', $user->usr_id ) }}" aria-label="{{ __('Editar Usuario') }}">
                        @csrf
                        <input type="hidden" name="_method" value="PUT">


                        <div class="form-group row">
                            <label for="usr_name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre') }}</label>

                            <div class="col-md-6">
                                <input id="usr_name" type="text" value="{{ $user->usr_name }}" class="form-control{{ $errors->has('usr_name') ? ' is-invalid' : '' }}" name="usr_name" value="{{ old('usr_name') }}" required autofocus>

                                @if ($errors->has('usr_name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('usr_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="usr_username" class="col-md-4 col-form-label text-md-right">{{ __('Usuario') }}</label>

                            <div class="col-md-6">
                                <input id="usr_username" type="text" value="{{ $user->usr_username }}" class="form-control{{ $errors->has('usr_username') ? ' is-invalid' : '' }}" name="usr_username" value="{{ old('usr_username') }}" required autofocus>

                                @if ($errors->has('usr_username'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('usr_username') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="usr_email" class="col-md-4 col-form-label text-md-right">{{ __('Correo Electrónico') }}</label>

                            <div class="col-md-6">
                                <input id="usr_email" type="email" value="{{ $user->usr_email }}" class="form-control{{ $errors->has('usr_email') ? ' is-invalid' : '' }}" name="usr_email" value="{{ old('usr_email') }}" required>

                                @if ($errors->has('usr_email'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('usr_email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="usr_city" class="col-md-4 col-form-label text-md-right">{{ __('Ciudad') }}</label>

                            <div class="col-md-6">
                                <input id="usr_city" type="text" value="{{ $user->usr_city }}" class="form-control{{ $errors->has('usr_city') ? ' is-invalid' : '' }}" name="usr_city" value="{{ old('usr_city') }}" required autofocus>

                                @if ($errors->has('usr_city'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('usr_city') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="hobbies" class="col-md-4 col-form-label text-md-right">{{ __('Pasatiempos') }}</label>

                            <div class="col-md-6">
                              <input id="hobbies" type="text" value="{{ $user->hobby }}" class="form-control{{ $errors->has('hobbies') ? ' is-invalid' : '' }}" name="hobbies" value="{{ old('hobbies') }}" required autofocus>
                              Agrega las variables con comas (,)
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Editar') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    Bienvenido {{ Auth::user()->usr_name }} 
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Iniciar Sesión') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Regístrate') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->usr_name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    @if (Auth::user()->profile->pro_name == 'administrator')
                                        <a class="dropdown-item" href="{{ route('users.index') }}">
                                            Usuarios
                                        </a>    
                                    @endif

                                    <a class="dropdown-item" href="{{ route('profile') }}">
                                        Perfil
                                    </a>    
                                    
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Cerrar Sesión') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/profile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Editar Mi Usuario') }}</div>

                <div class="card-body">
                    @if (session('status'))
                      <div class="alert alert-success">
                          {{ session('status') }}
                      </div>
                    @endif

                    <form method="POST" action="{{ route('profile_update') }}" aria-label="{{ __('Editar Mi Usuario') }}">
                        @csrf
                        <input type="hidden" name="_method" value="PUT">


                        <div class="form-group row">
                            <label for="usr_name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre') }}</label>

                            <div class="col-md-6">
                                <input id="usr_name" type="text" value="{{ $user->usr_name }}" class="form-control{{ $errors->has('usr_name') ? ' is-invalid' : '' }}" name="usr_name" value="{{ old('usr_name') }}" required autofocus>

                                @if ($errors->has('usr_name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('usr_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="usr_username" class="col-md-4 col-form-label text-md-right">{{ __('Usuario') }}</label>

                            <div class="col-md-6">
                                <input id="usr_username" type="text" value="{{ $user->usr_username }}" class="form-control{{ $errors->has('usr_username') ? ' is-invalid' : '' }}" name="usr_username" value="{{ old('usr_username') }}" required autofocus>

                                @if ($errors->has('usr_username'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('usr_username') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="usr_email" class="col-md-4 col-form-label text-md-right">{{ __('Correo Electrónico') }}</label>

                            <div class="col-md-6">
                                <input id="usr_email" type="email" value="{{ $user->usr_email }}" class="form-control{{ $errors->has('usr_email') ? ' is-invalid' : '' }}" name="usr_email" value="{{ old('usr_email') }}" required>

                                @if ($errors->has('usr_email'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('usr_email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="usr_city" class="col-md-4 col-form-label text-md-right">{{ __('Ciudad') }}</label>

                            <div class="col-md-6">
                                <input id="usr_city" type="text" value="{{ $user->usr_city }}" class="form-control{{ $errors->has('usr_city') ? ' is-invalid' : '' }}" name="usr_city" value="{{ old('usr_city') }}" required autofocus>

                                @if ($errors->has('usr_city'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('usr_city') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="hobbies" class="col-md-4 col-form-label text-md-right">{{ __('Pasatiempos') }}</label>

                            <div class="col-md-6">
                              <input id="hobbies" type="text" value="{{ $user->hobby }}" class="form-control{{ $errors->has('hobbies') ? ' is-invalid' : '' }}" name="hobbies" value="{{ old('hobbies') }}" required autofocus>
                              Agrega las variables con comas (,)
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Editar') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                      <div class="alert alert-success">
                          {{ session('status') }}
                      </div>
                    @endif

                    <table class="table">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Usuario</th>
                          <th scope="col">Nombre</th>
                          <th scope="col">Ciudad</th>
                          <th scope="col">Tipo de Perfil</th>
                          <th scope="col">Creado</th>
                          <th scope="col">Modificado</th>
                          <th scope="col">Acción</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach ($users as $user)
                          <tr>
                            <th scope="row">{{ $user->usr_id }} </th>
                            <td> {{ $user->usr_username }}</td>
                            <td> {{ $user->usr_email }}</td>
                            <td> {{ $user->usr_city }}</td>
                            <td> {{ $user->profile->pro_name }}</td>
                            <td> {{ $user->created_at }}</td>
                            <td> {{ $user->updated_at }}</td>
                            <td> <a class="btn btn-primary" href="{{ route('users.edit', $user->usr_id) }}" role="button"><i class="fas fa-edit"></i></a></td>
                          </tr>    
                        @endforeach
                        
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection